# See http://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: nosetests --with-coverage --cover-package=api
after_success:
  coveralls

